[package]
name = "ecs_rust"
version = "0.0.1"
description = "ECS in Rust"
authors = ["Takahiro <hogehoge@gachapin.jp>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/takahirox/ecs-rust"
repository = "https://github.com/takahirox/ecs-rust"
